# Generated by Django 4.2 on 2023-07-22 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0002_alter_shoppingsession_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingsession',
            name='delete_at',
        ),
    ]
